version: "3.7"

services:
  app-java:
    build: .
    container_name: la_concierge_ocupacao
    ports:
      - 8080:8080
    
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://172.25.0.2:5432/la_concierge_auth
      - SPRING_DATASOURCE_USERNAME=laconcierge
      - SPRING_DATASOURCE_PASSWORD=laconcierge
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - jwt_secret=4ec1353ccbf2721e678d0dd099d4562e
    
    networks:
      -   network-example
networks:
  network-example:
    external: true