version: "3.7"

services:
  app-java:
    build: .
    container_name: la_concierge_ocupacao

    env_file: ./.env

    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://$PGDB_URL:$PGDB_LOCAL_PORT/$PGDB_DATABASE
      - SPRING_DATASOURCE_USERNAME=$PGDB_USER
      - SPRING_DATASOURCE_PASSWORD=$PGDB_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=$SPRING_JPA_HIBERNATE_DDL_AUTO
      - jwt_secret=$JWT_SECRET

    networks:
      - network-example

networks:
  network-example:
    external: true
